Neos:
  ContentRepositoryRegistry:
    presets:
      'default':

        userIdProvider:
          factoryObjectName: Neos\Neos\UserIdProvider\UserIdProviderFactory

        contentRepositoryProjection:
          catchUpHooks:
            'Neos.Neos:FlushContentCache':
              factoryObjectName: Neos\Neos\Fusion\Cache\GraphProjectorCatchUpHookForCacheFlushingFactory
            'Neos.Neos:AssetUsage':
              factoryObjectName: Neos\Neos\AssetUsage\CatchUpHook\AssetUsageCatchUpHookFactory

        projections:
          'Neos.Neos:DocumentUriPathProjection':
            factoryObjectName: Neos\Neos\FrontendRouting\Projection\DocumentUriPathProjectionFactory
            catchUpHooks:
              'Neos.Neos:FlushRouteCache':
                factoryObjectName: Neos\Neos\FrontendRouting\CatchUpHook\RouterCacheHookFactory

          'Neos.Neos:PendingChangesProjection':
            factoryObjectName: Neos\Neos\PendingChangesProjection\ChangeProjectionFactory
